export const FETCH_POST_START="FETCH_POST_START";
export const FETCH_POST_SUCCESS="FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL="FETCH_POST_FAIL";
export const USER_DELETE="USER_DELETE";
export const USER_EDIT="USER_EDIT";